$PREVD = $pwd

### The following 3 lines copy the socpinfo file generated by your quartus project
### to your eclipse project directory.
### Updatye the name of the file to the correct name for your generated sopcinfo file
Set-Location $EP
log "Copying socpinfo file."
Copy-Item "$QP/first_nios2_system.sopcinfo" $EP

log "Generating new BSP files."
nios2-bsp-generate-files.exe --settings "software/${EP_NAME}_bsp/settings.bsp" --bsp-dir "software/${EP_NAME}_bsp" > $null

Set-Location "$EP/software/${EP_NAME}_bsp"
log "Building BSP project"
# & 'Nios II Command Shell.bat' make clean > $null
& 'Nios II Command Shell.bat' make all > $null
Set-Location "$EP/software/$EP_NAME" 
log "Building Project"
# & 'Nios II Command Shell.bat' make clean > $null
& 'Nios II Command Shell.bat' make all > $null

# [console]::beep(500,1000)

Set-Location $PREVD
